"$schema" = "node_modules/wrangler/config-schema.json"

compatibility_date = "2025-06-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

name = "scopedb-docs-next"
main = ".open-next/worker.js"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true
